- name: copy 
  synchronize:
    src: "{{ src_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
        # - "--exclude=node_modules"
        - "--exclude=SADemoTest_iac"
        - "--exclude=.git"
        - "--exclude=.gitignore"
        - "--exclude=README.md"
        - "--exclude=SADemoTest_iac@tmp"
  tags:
    - copy_files
- name: copy iac scripts
  synchronize:
    src: "{{ iac_src_dir }}"
    dest: "{{ iac_dest_dir }}"
    # rsync_opts:
    #     # - "--exclude=node_modules"
    #     - "--exclude=SADemoTest_iac"
    #     - "--exclude=.git"
    #     - "--exclude=.gitignore"
    #     - "--exclude=README.md"
    #     - "--exclude=SADemoTest_iac@tmp"
  tags:
    - copy_files